server:
  port: 8080

spring:
  application:
    name: order_service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:ordersdb
