spring:
  application:
    name: payment_service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payments-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:paymentsdb

server:
  port: 8081
