server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:ordersdb
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
