server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:paymentsdb

  h2:
    console:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      payment:
        topic:
          name: new-payments
      order:
        reverse:
          topic:
            name: reversed-orders    
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      order:
        topic:
          name: new-orders
      group-id: payments-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client: TRACE
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.client.loadbalancer: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
